all:
  children:
    frontend:
      hosts:
        preprod-frontend-1:
          ansible_host: 10.0.1.10
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/preprod-key.pem
    backend:
      hosts:
        preprod-backend-1:
          ansible_host: 10.0.10.10
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/preprod-key.pem
    monitoring:
      hosts:
        preprod-monitoring-1:
          ansible_host: 10.0.1.20
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/preprod-key.pem
  vars:
    env: preprod
