apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: fullstack-app
type: Opaque
data:
  host: <base64-encoded-db-host>
  username: <base64-encoded-db-username>
  password: <base64-encoded-db-password>
  database: <base64-encoded-db-name>
