name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: primordial-port-462408-q7
  GCP_REGION: europe-west1
  GCP_ZONE: europe-west1-b
  TERRAFORM_VERSION: 1.5.0

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check if frontend exists
        id: check_frontend
        run: |
          if [ -d "frontend" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Frontend directory does not exist, skipping npm steps"
          fi

      - name: Cache node_modules
        if: steps.check_frontend.outputs.exists == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies with retry
        if: steps.check_frontend.outputs.exists == 'true'
        run: |
          cd frontend
          for i in 1 2 3; do
            npm ci && break || sleep 10
          done   

      - name: Run tests with coverage
        if: steps.check_frontend.outputs.exists == 'true'
        run: |
          cd frontend
          npm run test:coverage

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    strategy:
      matrix:
        environment: [preprod, prod]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI 
        uses: google-github-actions/setup-gcloud@v1
        with: 
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Terraform Backend
        run: |
          cd terraform
          cat > backend.tf << 'EOF'
          terraform {
            backend "gcs" {
              bucket = "${{ secrets.TERRAFORM_STATE_BUCKET }}"
              prefix = "${{ matrix.environment }}/terraform/state"
            }
          }
          EOF

      - name: Create service account key file
        run: |
          cd terraform
          echo '${{ secrets.GCP_SA_KEY }}' > service-account-key.json

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="environment=${{ matrix.environment }}" \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
            -var="zone=${{ env.GCP_ZONE }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
            -out=tfplan-${{ matrix.environment }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: terraform/tfplan-${{ matrix.environment }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    strategy:
      matrix:
        environment: [preprod, prod]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:  
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: terraform/

      - name: Configure Terraform Backend
        run: |
          cd terraform
          cat > backend.tf << 'EOF'
          terraform {
            backend "gcs" {
              bucket = "${{ secrets.TERRAFORM_STATE_BUCKET }}"
              prefix = "${{ matrix.environment }}/terraform/state"
            }
          }
          EOF

      - name: Create service account key file
        run: |
          cd terraform
          echo '${{ secrets.GCP_SA_KEY }}' > service-account-key.json

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Handle existing resources
        run: |
          cd terraform
          import_if_exists() {
            local resource_type=$1
            local resource_name=$2
            local gcp_resource_id=$3
            if ! terraform state show "$resource_type.$resource_name" >/dev/null 2>&1; then
              echo "Tentative d'import de $resource_type.$resource_name..."
              terraform import "$resource_type.$resource_name" "$gcp_resource_id" || {
                echo "Import échoué, suppression de la ressource existante..."
                case $resource_type in
                  "google_compute_network")
                    gcloud compute networks delete $resource_name --quiet || true
                    ;;
                  "google_compute_health_check")
                    gcloud compute health-checks delete $resource_name --global --quiet || true
                    ;;
                  "google_compute_global_address")
                    gcloud compute addresses delete $resource_name --global --quiet || true
                    ;;
                  "google_service_account")
                    gcloud iam service-accounts delete "${resource_name}@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com" --quiet || true
                    ;;
                esac
              }
            fi
          }
          import_if_exists "google_compute_network" "main" "projects/${{ env.GCP_PROJECT_ID }}/global/networks/fullstack-app-vpc"
          import_if_exists "google_compute_health_check" "frontend" "projects/${{ env.GCP_PROJECT_ID }}/global/healthChecks/fullstack-app-frontend-hc"
          import_if_exists "google_compute_health_check" "backend" "projects/${{ env.GCP_PROJECT_ID }}/global/healthChecks/fullstack-app-backend-hc"
          import_if_exists "google_compute_global_address" "default" "projects/${{ env.GCP_PROJECT_ID }}/global/addresses/fullstack-app-lb-ip"
          import_if_exists "google_service_account" "compute" "projects/${{ env.GCP_PROJECT_ID }}/serviceAccounts/fullstack-app-compute-sa@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan-${{ matrix.environment }}

  build-and-deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    strategy:
      matrix:
        environment: [preprod, prod]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:    
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${{ github.sha }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${{ github.sha }}

      - name: Deploy to GKE (Production only)
        if: matrix.environment == 'prod'
        run: |
          gcloud container clusters get-credentials fullstack-app-gke-cluster --region=${{ env.GCP_REGION }}
          kubectl set image deployment/frontend-deployment frontend=gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${{ github.sha }}
          kubectl rollout status deployment/frontend-deployment
          kubectl rollout status deployment/backend-deployment

      - name: Update Compute Engine instances
        if: matrix.environment == 'preprod'
        run: |
          INSTANCE_GROUP=$(gcloud compute instance-groups managed list --filter="name~fullstack-app-frontend" --format="value(name)" --limit=1)
          gcloud compute instance-groups managed rolling-action start-update $INSTANCE_GROUP \
            --version=template=fullstack-app-frontend-$(date +%s) \
            --zone=${{ env.GCP_ZONE }}

  monitoring-setup:
    name: Setup Monitoring
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:    
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Create Monitoring Dashboards
        run: |
          gcloud monitoring dashboards create --config-from-file=monitoring/gcp-dashboard.json

      - name: Setup Alerting Policies
        run: |
          gcloud alpha monitoring policies create --policy-from-file=monitoring/alert-policies.yaml

  notify-deployment:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [monitoring-setup]
    if: always()
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          text: |
            Deployment to GCP completed!
            Environment: production
            Status: ${{ job.status }}
            Commit: ${{ github.sha }}
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 

      - name: Log deployment status
        run: |
          echo "Deployment completed with status: ${{ job.status }}"
          echo "Slack notification sent if webhook was configured."
